/**
 * DB SQL v2.0 資料表 / RPC 名稱對照。
 * 程式碼一律從這裡取名稱，避免字串散落；schema 變更時只改這裡。
 */
export const TABLES = {
  cms: {
    adminProfiles: 'admin_profiles',
    siteSettings: 'cms_site_settings',
    assets: 'cms_assets',
    pages: 'cms_pages',
    pageSections: 'cms_page_sections',
    seoMetadata: 'seo_metadata',
    seoRedirects: 'seo_redirects',
    navigationMenus: 'cms_navigation_menus',
    navigationItems: 'cms_navigation_items',
    blogPosts: 'blog_posts',
    faqs: 'faqs',
    contactInquiries: 'contact_inquiries',
    auditLogs: 'audit_logs',
    customerProfiles: 'customer_profiles',
  },
  commerce: {
    products: 'commerce_products',
    prices: 'commerce_product_prices',
    checkoutSessions: 'commerce_checkout_sessions',
    orders: 'commerce_orders',
    orderItems: 'commerce_order_items',
    payments: 'commerce_payments',
    paymentTransactions: 'commerce_payment_transactions',
    providerConfigs: 'commerce_payment_provider_configs',
    paymentMethods: 'commerce_payment_methods',
    bankTransferAccounts: 'commerce_bank_transfer_accounts',
    coupons: 'commerce_coupons',
    refunds: 'commerce_refunds',
    webhookEvents: 'commerce_webhook_events',
  },
  subscription: {
    plans: 'subscription_plans',
    planPrices: 'subscription_plan_prices',
    planFeatures: 'subscription_plan_features',
    customerSubscriptions: 'customer_subscriptions',
    periods: 'subscription_periods',
    invoices: 'subscription_invoices',
    cancellations: 'subscription_cancellations',
  },
  entitlement: {
    features: 'entitlement_features',
    products: 'entitlement_products',
    featureRules: 'entitlement_feature_rules',
    accessCodes: 'access_codes',
    accessCodeRedemptions: 'access_code_redemptions',
    accessCodeTransfers: 'access_code_transfers',
    userEntitlements: 'user_entitlements',
    usageQuotas: 'entitlement_usage_quotas',
    usageEvents: 'entitlement_usage_events',
  },
  workspace: {
    workspaces: 'customer_workspaces',
    members: 'customer_workspace_members',
    invitations: 'customer_workspace_invitations',
    settings: 'customer_workspace_settings',
  },
  siteBuilder: {
    projects: 'customer_site_projects',
    projectSettings: 'customer_site_project_settings',
    pages: 'customer_site_pages',
    sections: 'customer_site_sections',
    sectionFields: 'customer_site_section_fields',
    contentValues: 'customer_site_content_values',
    themeSettings: 'customer_site_theme_settings',
    navigationMenus: 'customer_site_navigation_menus',
    navigationItems: 'customer_site_navigation_items',
    footerSettings: 'customer_site_footer_settings',
    assets: 'customer_site_assets',
    forms: 'customer_site_forms',
    formFields: 'customer_site_form_fields',
    formSubmissions: 'customer_site_form_submissions',
    publishSettings: 'customer_site_publish_settings',
    releases: 'customer_site_deployments',
  },
  template: {
    templates: 'site_templates',
    versions: 'site_template_versions',
    categories: 'site_template_categories',
    licenses: 'site_template_licenses',
    purchases: 'site_template_purchases',
    previewSites: 'site_template_preview_sites',
  },
  domain: {
    domains: 'site_project_domains',
    verifications: 'site_domain_verifications',
    dnsInstructions: 'site_dns_instructions',
    dnsProviderGuides: 'site_dns_provider_guides',
    sslCertificates: 'site_ssl_certificates',
    publishTargets: 'site_publish_targets',
    deployments: 'site_deployments',
    checkLogs: 'site_domain_check_logs',
  },
  ai: {
    brandProfiles: 'ai_article_brand_profiles',
    projects: 'ai_article_projects',
    keywords: 'ai_article_keywords',
    generations: 'ai_article_generations',
    outputs: 'ai_article_generation_outputs',
    exports: 'ai_article_exports',
    usageCredits: 'ai_article_usage_credits',
    usageEvents: 'ai_article_usage_events',
    reviewLogs: 'ai_article_review_logs',
  },
  external: {
    connections: 'external_project_connections',
    syncLogs: 'external_project_sync_logs',
    cmsMappings: 'external_project_cms_mappings',
  },
} as const;

/** 業務動作一律走 RPC（SECURITY DEFINER，交易安全） */
export const RPC = {
  redeemAccessCode: 'redeem_access_code',
  transferAccessCode: 'transfer_access_code',
  revokeAccessCode: 'revoke_access_code',
  createWorkspaceFromAccessCode: 'create_workspace_from_access_code',
  createSiteProjectFromTemplate: 'create_site_project_from_template',
  publishSiteProject: 'publish_site_project',
  submitSiteForm: 'submit_site_form',
  generateDnsInstruction: 'generate_dns_instruction',
  addSiteProjectDomain: 'add_site_project_domain',
  getEnabledPaymentMethods: 'get_enabled_payment_methods',
  getBankTransferInstructions: 'get_bank_transfer_instructions',
  requestSubscriptionCancellation: 'request_subscription_cancellation',
  consumeAiArticleCredits: 'consume_ai_article_credits',
  // 以下僅限 server（service role / 森映 admin）
  markPaymentSuccessAndIssueEntitlement: 'mark_payment_success_and_issue_entitlement',
  recordSubscriptionRenewal: 'record_subscription_renewal',
  runEntitlementExpiryJob: 'run_entitlement_expiry_job',
} as const;
